### ISSUE TITLE
kwallet-add crashes krunner

### ISSUE THREAD

**Issue by kupiqu** [alex1701c/krunner-kwallet#1]
Trying to add an entry crashes krunner in my system.

System info:

Operating System: KDE neon 5.17
KDE Plasma Version: 5.17.4
KDE Frameworks Version: 5.65.0
Qt Version: 5.13.2

**Comment by alex1701c** [comment]
Hello,

can you please check if the latest commit fixes the issue ? 😃

**Comment by kupiqu** [comment]
Yes, it works now :)
