### ISSUE TITLE
Type kwl instead of kwallet ?

### ISSUE THREAD

**Issue by kupiqu** [alex1701c/krunner-kwallet#2]
kwl is the extension of kwallet files.

the advantage of kwl is that it requires a bit less typing and it does not interfere with other kwallet options:

- kwl and kwl-add instead of kwallet and kwallet-add
- only this runner would show, not the application, not the system setting, etc.

the cons is that it is a bit less obvious what it is, but people using this runner would rapidly get it, I think.

**Comment by alex1701c** [comment]
Hello,
I implemented your suggestions as extra keywords.
This means that you can use the plugin by typing `kwallet test` or `kwl test` and you get the same results.

And thanks for your feedback ! 😃

**Comment by kupiqu** [comment]
Excellent, thanks
