### ISSUE TITLE
Doesn't work w Plasma 6

### ISSUE THREAD

**Issue by rafrombrc** [alex1701c/krunner-kwallet#3]
I'm running Arch which has recently updated to Plasma 6 and sadly my krunner kwallet plugin is no longer working. I've tried installing through the KDE settings UI as well as from source; all of the files end up in the specified locations, but the kwallet plugin never shows up in the available plasma search plugins list.

Any chance you could update the runner to work on the new Plasma version?

Thanks!

**Comment by gitthangbaby** [comment]
how do you make it work on Plasma5? That's the only plugin i can't install:
Could NOT find KF5 (missing: Notifications) (found suitable version
"5.110.0", minimum required is "5.44.0")

**Comment by alex1701c** [comment]
I will try to port it this weekend :)

**Comment by rafrombrc** [comment]
@gitthangbaby I think I just activated krunner and clicked on the prefs icon to the left of the input space, which brought me to the `Plasma Search` section of the System Settings app. From there I clicked `Ge New Plugins...` and used the UI to find and install KWalletRunner. I think I tried installing from source first but didn't get it working that way. This was on Ubuntu Studio 22.04.

@alex1701c Great, thanks!

**Comment by alex1701c** [comment]
The state of master /might/ work with Qt6 now. But I do not seem to have a reasable wallet on my laptop, it will need a bit of debugging.

**Comment by rafrombrc** [comment]
It works! It didn't at first bc I was following the manual install instructions, but once I deleted the build dir and ran `install.sh` it started showing up in the plasma plugins list and now my passwords are available in krunner just like before.

Thank you!

**Comment by alex1701c** [comment]
Amazing! I will make a release then :))

**Comment by alex1701c** [comment]
I have fixed a crash for the dialogs now
